version: '3.9'

services:
    backend:
        container_name: backend
        networks:
            - internal-network
        build:
            context: ./backend/
        
    frontend:
        container_name: frontend
        networks:
            - internal-network
        build:
            context: ./frontend/
            
    reverse_proxy:
        container_name: reverseProxy
        networks:
            - internal-network
        ports:
            - 8080:80
        build:
            context: ./reverseProxy/
            
networks:
    internal-network: